/*1. Modificar el modelo (si es necesario) para almacenar el usuario de Oracle que cada empleado o cliente pueda
utilizar para conectarse a la base de datos. Adem�s habr� de crear roles dependiendo del tipo de usuario:
Administrativo, con acceso a toda la BD; Empleado, con acceso s�lo a aquellos objetos que precise para su
trabajo (y nunca podr� acceder a los datos de otros empleados); y Cliente, con acceso s�lo a los datos propios,
de su veh�culo y de sus servicios. Los roles se llamar�n R_ADMINISTRATIVO, R_MECANICO, R_CLIENTE.
*/

-- CREAMOS LOS ROLES:

CREATE ROLE R_ADMINISTRATIVO;
CREATE ROLE R_MECANICO;
CREATE ROLE R_CLIENTE;

-- DAMOS PERMISOS A LOS ROLES:

    -- PERMISOS COMUNES:
    GRANT CONNECT TO R_ADMINISTRATIVO, R_MECANICO, R_CLIENTE;
    
    -- PERMISOS A R_ADMINISTRADOR (TODA LA BD).
    /* NO USAR ANY, NO TENEMOS PRIVILEGIOS PARA ELLO EN AUTORACLE, ADEM�S ES PELIGROSO.
       RECORDAR QUE CADA VEZ QUE SE INTRODUZCA ALGO NUEVO A LA BD HAY QUE DARLE PERMISOS
       AL R_ADMINISTRADOR
    */
    
    GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON CITA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTE TO R_ADMINISTRATIVO;
    GRANT SELECT ON CLIENTE_EXTERNO TO R_ADMINISTRATIVO; -- TABLA EXTERNA, SOLO SELECT
    GRANT SELECT, INSERT, UPDATE, DELETE ON COMPATIBLE TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON COMPRA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON CONTIENE TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADO TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON EXAMEN TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON LOTE TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON MANTENIMIENTO TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON MARCA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON MODELO TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON MV_FACTURAS20 TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON NECESITA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON PIEZA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON PROVEE TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON PROVEEDOR TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON REPARACION TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON REQUIERE TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICIO TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON TRABAJA TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON VACACIONES TO R_ADMINISTRATIVO;
    GRANT SELECT, INSERT, UPDATE, DELETE ON VEHICULO TO R_ADMINISTRATIVO;
    

    -- PERMISOS NECESARIOS A R_MECANICO (NO ACCEDER A LOS DATOS DE OTRO MECANICO)
    /* VER LO DE NO OTRO MECANICO Y SI NECESITA M�S PRIVILEGIOS*/    

    
    -- PERMISO A LAS CLASES HIJAS DE SERVICIO
    GRANT SELECT ON MANTENIMIENTO TO R_MECANICO;
    GRANT SELECT ON REPARACION TO R_MECANICO;
    
    ALTER TABLE EMPLEADO ADD USERNAME VARCHAR(32);
    
       -- CADA EMPLEADO SOLO ACCEDE A SUS DATOS PROPIOS (A PARTIR DE UNA VISTA).
       
    CREATE OR REPLACE VIEW VDATOSEMPL AS (SELECT * FROM EMPLEADO WHERE UPPER(USERNAME) = UPPER(USER));
    
    CREATE OR REPLACE VIEW VFACTURA AS (SELECT * FROM FACTURA F JOIN EMPLEADO E ON (F.EMPLEADO_IDEMPLEADO=E.IDEMPLEADO) WHERE UPPER(E.USERNAME) = UPPER(USER));
    
    CREATE OR REPLACE VIEW VVACACIONES AS (SELECT V.*, E.NOMBRE, E.APELLIDO1, E.APELLIDO2, E.SUELDOBASE, E.HORAS, E.PUESTO FROM VACACIONES V JOIN EMPLEADO E ON (V.EMPLEADO_IDEMPLEADO=E.IDEMPLEADO) WHERE UPPER(E.USERNAME) = UPPER(USER));
    
    CREATE OR REPLACE VIEW VSERVICIO AS (SELECT * FROM SERVICIO S JOIN TRABAJA T ON (S.IDSERVICIO = T.SERVICIO_IDSERVICIO) JOIN EMPLEADO E ON (E.IDEMPLEADO = T.EMPLEADO_IDEMPLEADO) WHERE UPPER(E.USERNAME) = UPPER(USER));
    
    GRANT SELECT ON VDATOSEMPL TO R_MECANICO;
    GRANT SELECT ON VFACTURA TO R_MECANICO;
    GRANT SELECT ON VVACACIONES TO R_MECANICO;
    GRANT SELECT ON VSERVICIO TO R_MECANICO;
    
    -- PERMISO CLIENTES
    
    -- VISTA A DATOS PROPIOS.
    ALTER TABLE CLIENTE ADD USERNAME VARCHAR(32);
    
    CREATE OR REPLACE VIEW VDATOS AS (SELECT * FROM AUTORACLE.CLIENTE WHERE UPPER(USERNAME) = UPPER(USER)); -- username = user
    
    -- VISTA A SERVICIOS PROPIOS 
    
   CREATE OR REPLACE VIEW VSERVICIO AS
   (select * from servicio s join vehiculo v on (s.vehiculo_numbastidor=v.numbastidor) join cliente c on (v.cliente_idcliente=c.idcliente) where UPPER(c.username) = UPPER(user));
    
    -- VISTA A VEHICULO PROPIO
     
    CREATE OR REPLACE VIEW VVEHICULO AS (SELECT * FROM vehiculo v join CLIENTE c on (v.CLIENTE_IDCLIENTE=c.IDCLIENTE) WHERE UPPER(C.USERNAME) = UPPER(USER));
    
    -- Dar permisos de la vista
    
    GRANT SELECT ON VDATOS TO R_CLIENTE;
    GRANT SELECT ON VSERVICIO TO R_CLIENTE;
    GRANT SELECT ON VVEHICULO TO R_CLIENTE;
    
    
    /* TESTEO */
    
    -- EMPLEADO 
    
    SELECT * FROM EMPLEADO;
    
    UPDATE EMPLEADO SET USERNAME = 'EMIL03' WHERE IDEMPLEADO = 117;
    
    create user EMIL03 identified by bd default tablespace TS_AUTORACLE
    QUOTA 1M on TS_AUTORACLE;
    
    GRANT R_MECANICO TO EMIL03;
    
    SELECT * FROM FACTURA;
    SELECT * FROM SERVICIO;
    
    INSERT INTO VACACIONES VALUES (43245, SYSDATE+30, SYSDATE+40, 1, 117);
    INSERT INTO FACTURA VALUES (1823, 12, 21, SYSDATE, 0, 117, 42, 567);
    INSERT INTO TRABAJA VALUES(117,18);
    
    COMMIT;
    
    /* DESDE EMIL03 
        select * from autoracle.vdatosempl;
        SELECT * FROM AUTORACLE.VFACTURA;
        SELECT * FROM AUTORACLE.VVACACIONES;
        SELECT * FROM AUTORACLE.VSERVICIO;
    */
    
    -- CLIENTE
    
    select * from VVEHICULO;
    select * from cliente;
    
    insert into CLIENTE values('123945', 676987890, 'Mike', 'Perez', 'Galvan', 'mike@uma.es', 'Mike32' );
    
    create user Mike32 identified by bd default tablespace TS_AUTORACLE
    QUOTA 1M on TS_AUTORACLE;
    
    grant R_CLIENTE to Mike32;
    select * from cliente;
    