/*3. Necesitamos una vista denominada V_IVA_CUATRIMESTRE con los atributos A�O, TRIMESTRE, IVA_TOTAL
siendo trimestre un n�mero de 1 a 4. El IVA_TOTAL es el IVA devengado (suma del IVA de las facturas de ese
trimestre). Dar permiso de selecci�n a los Administrativos. */

-- "" VER SI HAY ALGUNA FORMA M�S INTUITIVA O SENCILLA DE HACERLO ""

CREATE OR REPLACE VIEW V_IVA_CUATRIMESTRE (A�O, TRIMESTRE, IVA_TOTAL) AS
(SELECT TO_CHAR(FECEMISION,'YYYY'), TRUNC((TO_NUMBER(TO_CHAR(FECEMISION, 'MM'))/4)+1), SUM(IVA) AS IVA_TOTAL FROM FACTURA 
GROUP BY TO_CHAR(FECEMISION,'YYYY'), TRUNC((TO_NUMBER(TO_CHAR(FECEMISION, 'MM'))/4)+1));

SELECT * FROM V_IVA_CUATRIMESTRE;

GRANT SELECT ON V_IVA_CUATRIMESTRE TO R_ADMINISTRATIVO;
